---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/data-center-final-project/service-a:latest
        env:
          - name: GCP_CRED
            valueFrom:
              secretKeyRef:
                name: data-center-project-secret
                key: GCP_CRED
          - name: TRAIN_TRACKER_KEY
            valueFrom:
              secretKeyRef:
                name: data-center-project-secret
                key: TRAIN_TRACKER_KEY
          - name: PORT
            value: "8080"
          - name: DEBUG
            value: "FALSE"
          - name: TOPIC_ID
            value: "bus-data"
          - name: PROJECT_ID
            value: "civic-automata-435117-h3"